name: Project1
description: A starting point for Dart libraries or applications.
version: 0.0.1
#homepage: https://www.example.com
#author: maksim <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  http_server: any
  route: any
  # postgres: "^0.9.6"
  mapper:
      git: git@repo.centryl.org:centryl/mapper.git

dev_dependencies:
  test: ^0.12.0
